# Generated by Django 2.1 on 2018-08-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nome',
            field=models.CharField(max_length=300),
        ),
    ]
