# Generated by Django 2.1 on 2018-08-27 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180827_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pais',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
